---
title: "Manual for luckyExperiment"
author: 
- name: Weibin Huang
  email: 654751191@qq.com
  affiliation: First affiliated hospital, Sun Yat-sen University
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Manual for luckyExperiment}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r style, echo=FALSE, results="asis", message=FALSE}
knitr::opts_chunk$set(tidy = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

# Overview
It's a tool for the analysis of some biological experiments, such as qPCR.

## FastQPCR

### package
```{r}
library(luckyExperiment)
package.need <- c('tidyr','readxl')
for( i in package.need){
  if (!requireNamespace(i, quietly = TRUE)){
    install.packages(i)
    library(i,character.only = T)
  } else {
    library(i,character.only = T)
 }
} 

```

### example data
```{r}

data <- system.file("extdata","testData_qPCR.xlsx", package = "luckyExperiment") %>% read_xlsx %>% as.data.frame
View(data)

```

### FastQPCR analysis

```{r}
result_qpcr <- FastQPCR(data,
                        sample = "samples", 
                        marker = "markers",
                        bioRepeat = "biorepeat", 
                        parallelRepeat = "parepeat",
                        group = "groups", 
                        group.control = "sh-Negative", 
                        internal = "GAPDH",
                        value = "Ct", 
                        plot.type = 1, # one marker
                        palette = NULL,
                        size = 20, 
                        label.position  = c(1,1.5),
                        label.type = "p.format",
                        method =  "anova",
                        x.title = "Groups", 
                        y.title = "The Relative Expression of Genes",
                        legend.position = "top")

# result
View(result_qpcr$Data$metadata)
View(result_qpcr$Data$statistc$whole)
View(result_qpcr$Data$statistc$pair) 

```





















